### ISSUE TITLE
UnhandledPromiseRejectionWarning:  Unhandled promise rejection (rejection id: 1): [object Object]

### ISSUE THREAD

**Issue by asingh12541** [mirusresearch/firehoser#5]
Hi It' shows error:
(node:8676) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]

TIA

**Comment by EyePulp** [comment]
Howdy;
Can you provide a full stack trace or possibly a test case that demonstrates this error?  Without either of those diagnosis will be very difficult.  Thanks!

**Comment by EyePulp** [comment]
Closing until further info is provided.
